name: CI Check

on: [workflow_dispatch, push]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run codegen
      - run: npm run build
      - run: npm run lint
